class Main inherits IO {
    main(): Object {
    { 
      self.out_string(
    "Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nnnHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nnHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nnnHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\Hellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nHellow World!\nHow\t\a\r\e\tyou\nnnnnn"
  );
  out_string ("Hello World!\n");
  };

};
